# training configuration
checkpoint_path = "saved_models"
start_from = None
learning_rate = 1.
epochs = 20
xe_base_lr = 1e-4
rl_base_lr = 5e-6
refine_epoch_rl = 28
xe_least = 15
xe_most = 20
min_freq = 3

# model configuration
model_name = "m2-transformer"
total_memory = 40
nhead = 8
nlayers = 4
d_model = 512
d_k = 64
d_v = 64
d_ff = 2048
d_feature = 2048
dropout = .1
beam_size = 5

# dataset configuration
train_json_path = "features/region_features/UIT-ViIC/uitviic_captions_train2017.json"
val_json_path = "features/region_features/UIT-ViIC/uitviic_captions_val2017.json"
test_json_path = "features/region_features/UIT-ViIC/uitviic_captions_test2017.json"
feature_path = "features/region_features/UIT-ViIC/faster_rcnn"
batch_size = 16
workers = 2